services:
  - type: web
    name: jojospeed-api
    runtime: node
    plan: free
    region: frankfurt
    rootDir: api
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: jojospeed
    runtime: static
    buildCommand: echo "no build"
    staticPublishPath: web/public
